import Head from "next/head";
import Footer from "./Footer";

const Layout = ({ children }) => {
  return (
    <div className="flex flex-col h-screen justify-between">
      <Head>
        <link rel="icon" href="logo.png" />
        <title>Próximo Feriado</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className=" mt-auto mb-auto">{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
