import Head from "next/head";
const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">holanda</h1>
      <main>{children}</main>
    </>
  );
};

export default Layout;
